#include "plugins/encryption/crypto_tests.cpp"
#include "adapters/database/databaseInterface_tests.cpp"
#include "application/encryptor_tests.cpp"
#include "application/factory_tests.cpp"
#include "application/repository_tests.cpp"
